timeout: "1200s"

steps:
  - id: "install dependencies"
    name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args:
      - "install"

  - id: "build app"
    name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args:
      - "run"
      - "build"
    secretEnv: ["REACT_APP_FIREBASE_API_KEY"]

  - id: "deploy with firebase"
    name: "gcr.io/todo-gcloud/firebase"
    args: ["deploy", "--project=todo-gcloud", "--only=hosting"]
    secretEnv: ["FIREBASE_TOKEN"]

  - id: "test with cypress"
    name: "cypress/included:10.8.0"
    entrypoint: "yarn"
    args:
      - "run"
      - "e2e"

  - id: "upload e2e screenshots"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - "-e"
      - |
        if [ -d "./cypress/screenshots" ] && [ -n "$(ls -A ./cypress/screenshots 2>/dev/null)" ]; then
          gsutil -m cp -r ./cypress/screenshots/* gs://todo_app_csornyei/screenshots
        fi

availableSecrets:
  secretManager:
    - versionName: projects/todo-gcloud/secrets/firebase_api_key/versions/1
      env: "REACT_APP_FIREBASE_API_KEY"
    - versionName: projects/todo-gcloud/secrets/firebase_ci_key/versions/1
      env: "FIREBASE_TOKEN"
